name: Deploy App to Development server

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: DEVELOPMENT
    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/firstry-development-back:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/firstry-development-back:latest

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd FIRSTRY

            echo "ENV=${{ secrets.ENV_ENV }}" > .envDevBack
            echo "DB_HOST=${{ secrets.ENV_DB_HOST }}" >> .envDevBack
            echo "APP_URL=${{ secrets.ENV_APP_URL }}" >> .envDevBack
            echo "FIREBASE_CLIENT_EMAIL=${{ secrets.ENV_FIREBASE_CLIENT_EMAIL }}" >> .envDevBack
            echo "FIREBASE_PRIVATE_KEY=${{ secrets.ENV_FIREBASE_PRIVATE_KEY }}" >> .envDevBack
            echo "FIREBASE_PROJECT_ID=${{ secrets.ENV_FIREBASE_PROJECT_ID }}" >> .envDevBack
            echo "FIREBASE_STORAGE_BUCKET=${{ secrets.ENV_FIREBASE_STORAGE_BUCKET }}" >> .envDevBack
            echo "JWT_SECRET_TOKEN=${{ secrets.ENV_JWT_SECRET_TOKEN }}" >> .envDevBack
            echo "NODE_MAILER_PASS=${{ secrets.ENV_NODE_MAILER_PASS }}" >> .envDevBack

            docker compose -f docker-compose.dev.yml pull
            docker compose -f docker-compose.dev.yml -p firstry-dev up -d
            docker system prune -f
